# Generated by Django 5.0 on 2024-03-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0003_auto_20240318_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='reference_no',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
