# Generated by Django 5.0 on 2024-03-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0004_creditnote_reference_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnotereference',
            name='reference_no',
        ),
    ]
