# Generated by Django 5.0 on 2024-03-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0005_remove_creditnotereference_reference_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnotereference',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
