# Generated by Django 5.0 on 2024-03-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0006_creditnotereference_reference_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnotereference',
            name='credit_note',
        ),
    ]
