# Generated by Django 5.0 on 2024-03-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0007_remove_creditnotereference_credit_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='reference_no',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
